### PR TITLE
change(license): use GPLv2 instead of MIT to comply with upstream licenses (Qt/QGIS)

### PR DESCRIPTION
**Pull request by Guts**
Even if the MIT license was not really applicable, I guess it's would be better to ask every contributor who commit to this project to grant this change by commenting this PR:

- [x] @dszillWG
- [x] @kannes
- [x] @pigreco
- [x] @ivn951
- [x] @lbartoletti

----

- Related to https://github.com/WhereGroup/profile-manager/issues/10
- :heart: Funded by [Oslandia](https://oslandia.com/) and [ANFSI](https://www.linkedin.com/company/anfsi/about/).

### CODE REVIEW

**Comment by lbartoletti** [comment]
MIT/BSD license is my natural license 😜 , but yeah, it's ok for me 👍

**Comment by kannes** [comment]
Same for our work but yeah, the GPL is binding :)

I will tick the mark for @dszillWG too as his and my developments were on company orders and we are ok with this change. It was merely an oversight.

**Comment by Guts** [comment]
Hi @pigreco and @ivn951,

I'm taking the liberty of pinging you again so as not to lose momentum in our current development sprint.

Could you please tell us if you are OK with this change of license?

**Comment by pigreco** [comment]
@Guts 
Yes, no problem for me

**Comment by kannes** [comment]
Ping @ivn951

**Comment by ivn951** [comment]
> Even if the MIT license was not really applicable, I guess it's would be better to ask every contributor who commit to this project to grant this change by commenting this PR:
> 
> * [x]  @dszillWG
> * [x]  @kannes
> * [x]  @pigreco
> * [ ]  @ivn951
> * [x]  @lbartoletti
> 
> * Related to [Profile Manager x QGIS Deployment Toolbelt: an impacting contribution proposal #10](https://github.com/WhereGroup/profile_manager/issues/10)
> * ❤️ Funded by [Oslandia](https://oslandia.com/) and [ANFSI](https://www.linkedin.com/company/anfsi/about/).



> I've contacted @ivn951 through LinkedIn.

it's okay with me, too!

**Comment by Guts** [comment]
Here we gooo!

**Comment by kannes** [comment]
Excellent, thank you @ivn951 !

**Pull request merged**
